import type { Metadata } from "next"
import { Inter, Inter_Tight } from "next/font/google"

import "@/styles/globals.css"

import { cn } from "@/lib/utils"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "700"],
})

const interTight = Inter_Tight({
  subsets: ["latin"],
  variable: "--font-inter-tight",
  weight: ["700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn(inter.variable, interTight.variable, "antialiased")}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  )
}
